import { render, screen } from "@testing-library/react";
import { renderToStaticMarkup } from "react-dom/server";

import Page from "@/app/page";
import RootLayout, { metadata } from "@/app/layout";

describe("App smoke tests", () => {
  it("renders the home page without crashing", () => {
    render(<Page />);

    expect(screen.getByText(/welcome to the home page/i)).toBeInTheDocument();
  });

  it("keeps the root layout renderable", () => {
    const markup = renderToStaticMarkup(
      <RootLayout>
        <main data-testid="smoke-child">Smoke child</main>
      </RootLayout>,
    );

    expect(markup).toContain('<html lang="en"');
    expect(markup).toContain('data-testid="smoke-child"');
    expect(markup).toContain("Smoke child");
  });

  it("exports default app metadata", () => {
    expect(metadata).toMatchObject({
      title: "Create Next App",
      description: "Generated by create next app",
    });
  });
});
